// Shared Futbin internal nation_id → { iso, name } mapping.
//
// Single source of truth used by:
//   - _backfill_nationality.js (post-scrape backfill pass)
//   - _lib_diff_upsert.js       (scraper insert/update — top-level
//                                 nation_iso + nation columns)
//
// Curated 2026-05-01 against modal `nation` text in the live
// fc26_players table joined with the Kaggle-matched slugs (top 122
// IDs cover 100% of the 22.9k Futbin rows). Country names follow
// Futbin/EA's preferred form where it differs from the official ISO
// label (e.g. "Holland" not "Netherlands", "Korea Republic" not
// "South Korea"). ISO codes follow ISO 3166-1 alpha-2 except where
// FIFA carves out 3-char codes for non-sovereign territories
// (England=EN, Northern Ireland=NIR, Scotland=SCO, Wales=WAL).

const FUTBIN_NATION_MAP = {
  2: { iso: "AD", name: "Andorra" },
  1: { iso: "AL", name: "Albania" },
  3: { iso: "AM", name: "Armenia" },
  4: { iso: "AT", name: "Austria" },
  5: { iso: "AZ", name: "Azerbaijan" },
  6: { iso: "BY", name: "Belarus" },
  7: { iso: "BE", name: "Belgium" },
  8: { iso: "BA", name: "Bosnia and Herzegovina" },
  9: { iso: "BG", name: "Bulgaria" },
  10: { iso: "HR", name: "Croatia" },
  11: { iso: "CY", name: "Cyprus" },
  12: { iso: "CZ", name: "Czech Republic" },
  13: { iso: "DK", name: "Denmark" },
  14: { iso: "EN", name: "England" },
  15: { iso: "ME", name: "Montenegro" },
  16: { iso: "FO", name: "Faroe Islands" },
  17: { iso: "FI", name: "Finland" },
  18: { iso: "FR", name: "France" },
  19: { iso: "MK", name: "North Macedonia" },
  20: { iso: "GE", name: "Georgia" },
  21: { iso: "DE", name: "Germany" },
  22: { iso: "GR", name: "Greece" },
  23: { iso: "HU", name: "Hungary" },
  24: { iso: "IS", name: "Iceland" },
  25: { iso: "IE", name: "Republic of Ireland" },
  26: { iso: "IL", name: "Israel" },
  27: { iso: "IT", name: "Italy" },
  28: { iso: "LV", name: "Latvia" },
  29: { iso: "LI", name: "Liechtenstein" },
  30: { iso: "LT", name: "Lithuania" },
  31: { iso: "LU", name: "Luxembourg" },
  32: { iso: "MT", name: "Malta" },
  33: { iso: "MD", name: "Moldova" },
  34: { iso: "NL", name: "Holland" },
  35: { iso: "NIR", name: "Northern Ireland" },
  36: { iso: "NO", name: "Norway" },
  37: { iso: "PL", name: "Poland" },
  38: { iso: "PT", name: "Portugal" },
  39: { iso: "RO", name: "Romania" },
  40: { iso: "RU", name: "Russia" },
  42: { iso: "SCO", name: "Scotland" },
  43: { iso: "SK", name: "Slovakia" },
  44: { iso: "SI", name: "Slovenia" },
  45: { iso: "ES", name: "Spain" },
  46: { iso: "SE", name: "Sweden" },
  47: { iso: "CH", name: "Switzerland" },
  48: { iso: "TR", name: "Turkey" },
  49: { iso: "UA", name: "Ukraine" },
  50: { iso: "WAL", name: "Wales" },
  51: { iso: "RS", name: "Serbia" },
  52: { iso: "AR", name: "Argentina" },
  53: { iso: "BO", name: "Bolivia" },
  54: { iso: "BR", name: "Brazil" },
  55: { iso: "CL", name: "Chile" },
  56: { iso: "CO", name: "Colombia" },
  57: { iso: "EC", name: "Ecuador" },
  58: { iso: "PY", name: "Paraguay" },
  59: { iso: "PE", name: "Peru" },
  60: { iso: "UY", name: "Uruguay" },
  61: { iso: "VE", name: "Venezuela" },
  63: { iso: "AG", name: "Antigua and Barbuda" },
  66: { iso: "BB", name: "Barbados" },
  68: { iso: "BM", name: "Bermuda" },
  70: { iso: "CA", name: "Canada" },
  72: { iso: "CR", name: "Costa Rica" },
  73: { iso: "CU", name: "Cuba" },
  76: { iso: "SV", name: "El Salvador" },
  77: { iso: "GD", name: "Grenada" },
  78: { iso: "GT", name: "Guatemala" },
  79: { iso: "GY", name: "Guyana" },
  80: { iso: "HT", name: "Haiti" },
  81: { iso: "HN", name: "Honduras" },
  82: { iso: "JM", name: "Jamaica" },
  83: { iso: "MX", name: "Mexico" },
  84: { iso: "MS", name: "Montserrat" },
  85: { iso: "CW", name: "Curaçao" },
  87: { iso: "PA", name: "Panama" },
  88: { iso: "US", name: "United States" },
  89: { iso: "KN", name: "St. Kitts and Nevis" },
  90: { iso: "LC", name: "St. Lucia" },
  92: { iso: "SR", name: "Suriname" },
  93: { iso: "TT", name: "Trinidad and Tobago" },
  95: { iso: "US", name: "United States" },
  97: { iso: "DZ", name: "Algeria" },
  98: { iso: "AO", name: "Angola" },
  99: { iso: "BJ", name: "Benin" },
  101: { iso: "BF", name: "Burkina Faso" },
  102: { iso: "BI", name: "Burundi" },
  103: { iso: "CM", name: "Cameroon" },
  104: { iso: "CV", name: "Cape Verde Islands" },
  105: { iso: "CF", name: "Central African Republic" },
  106: { iso: "TD", name: "Chad" },
  107: { iso: "CG", name: "Congo" },
  108: { iso: "CI", name: "Côte d'Ivoire" },
  110: { iso: "CD", name: "Congo DR" },
  111: { iso: "EG", name: "Egypt" },
  112: { iso: "GQ", name: "Equatorial Guinea" },
  115: { iso: "GA", name: "Gabon" },
  116: { iso: "GM", name: "Gambia" },
  117: { iso: "GH", name: "Ghana" },
  118: { iso: "GN", name: "Guinea" },
  119: { iso: "GW", name: "Guinea-Bissau" },
  120: { iso: "KE", name: "Kenya" },
  122: { iso: "LR", name: "Liberia" },
  123: { iso: "LY", name: "Libya" },
  124: { iso: "MG", name: "Madagascar" },
  125: { iso: "MW", name: "Malawi" },
  126: { iso: "ML", name: "Mali" },
  127: { iso: "MR", name: "Mauritania" },
  129: { iso: "MA", name: "Morocco" },
  130: { iso: "MZ", name: "Mozambique" },
  131: { iso: "NA", name: "Namibia" },
  132: { iso: "NE", name: "Niger" },
  133: { iso: "NG", name: "Nigeria" },
  134: { iso: "RW", name: "Rwanda" },
  136: { iso: "SN", name: "Senegal" },
  138: { iso: "SL", name: "Sierra Leone" },
  139: { iso: "SO", name: "Somalia" },
  140: { iso: "ZA", name: "South Africa" },
  143: { iso: "TZ", name: "Tanzania" },
  144: { iso: "TG", name: "Togo" },
  145: { iso: "TN", name: "Tunisia" },
  146: { iso: "UG", name: "Uganda" },
  147: { iso: "ZM", name: "Zambia" },
  148: { iso: "ZW", name: "Zimbabwe" },
  149: { iso: "AF", name: "Afghanistan" },
  151: { iso: "BD", name: "Bangladesh" },
  155: { iso: "CN", name: "China PR" },
  158: { iso: "HK", name: "Hong Kong" },
  159: { iso: "IN", name: "India" },
  160: { iso: "ID", name: "Indonesia" },
  161: { iso: "IR", name: "Iran" },
  162: { iso: "IQ", name: "Iraq" },
  163: { iso: "JP", name: "Japan" },
  164: { iso: "JO", name: "Jordan" },
  167: { iso: "KR", name: "Korea Republic" },
  171: { iso: "LB", name: "Lebanon" },
  173: { iso: "MY", name: "Malaysia" },
  179: { iso: "PK", name: "Pakistan" },
  180: { iso: "PS", name: "Palestine" },
  181: { iso: "PH", name: "Philippines" },
  183: { iso: "SA", name: "Saudi Arabia" },
  185: { iso: "LK", name: "Sri Lanka" },
  186: { iso: "SY", name: "Syria" },
  187: { iso: "TJ", name: "Tajikistan" },
  188: { iso: "TH", name: "Thailand" },
  190: { iso: "AE", name: "United Arab Emirates" },
  191: { iso: "UZ", name: "Uzbekistan" },
  195: { iso: "AU", name: "Australia" },
  198: { iso: "NZ", name: "New Zealand" },
  204: { iso: "VU", name: "Vanuatu" },
  207: { iso: "DO", name: "Dominican Republic" },
  208: { iso: "EE", name: "Estonia" },
  213: { iso: "TW", name: "Chinese Taipei" },
  214: { iso: "KM", name: "Comoros" },
  215: { iso: "FR", name: "France" },
  219: { iso: "XK", name: "Kosovo" },
};

// Resolve a futbin_nation_id integer (or numeric string) to its ISO + name.
// Returns null when unmappable so callers can route to the unresolved log.
function resolveFutbinNation(id) {
  if (id == null) return null;
  const n = typeof id === "number" ? id : parseInt(String(id), 10);
  if (!Number.isFinite(n)) return null;
  return FUTBIN_NATION_MAP[n] ?? null;
}

module.exports = { FUTBIN_NATION_MAP, resolveFutbinNation };
