-- Switch the OAS partner logo entry to point at the colored variant.
-- New file shipped at /overlays/v2/_assets/logos/processed/OAS_colored_strip.png
-- (600×300, transparent bg) generated by sharp from
-- KNOWLEDGE/brand-assets/logos/OAS ESPORTS COLORED.png.
--
-- Affects the partner strip on every overlay that pulls the OAS logo
-- (01-brb, 12-starting-soon, 13-stream-ended, etc).
--
-- Idempotent: WHERE clause filters on partner_key + deleted_at to
-- avoid clobbering a freshly-soft-deleted row. The BACKFILL UPDATE
-- runs once; subsequent re-applies of the migration are no-ops since
-- the file_url is already set to the colored variant.

update public.overlay_partner_logos
set
  file_url = '/overlays/v2/_assets/logos/processed/OAS_colored_strip.png',
  updated_at = now()
where
  partner_key = 'oas'
  and deleted_at is null
  and file_url <> '/overlays/v2/_assets/logos/processed/OAS_colored_strip.png';
